export const features = {
  DECLARATION: true,
  SIGNING_WALL: true,
  CERTIFICATES: true,
  JAINZ_ID: true,
  BADGES: true,
  DASHBOARD: true,
  FOUNDER_DIRECTORY: true,
  STUDENT_DIRECTORY: true,
  PROFESSIONAL_DIRECTORY: true,
  VOLUNTEER_DIRECTORY: true,
  MENTOR_DIRECTORY: true,
  SANGH_DIRECTORY: true,
  TEMPLE_DIRECTORY: true,
  NGO_DIRECTORY: true,
  EVENTS: true,
  SEARCH: true,
  GLOBE: true,
  NAVKAR: true,
  ANALYTICS: true,
  ADMIN: true,
  JAINGPT: false,
  PASSPORT: false,
  LEARNING: false,
  JOBS: false,
  MARKETPLACE: false,
} as const;

export type FeatureKey = keyof typeof features;
